name: Preview Deployment (UI)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'ui/**'
      - '.github/workflows/preview-ui.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ui/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ui:pr-${{ github.event.pull_request.number }}

      - name: Deploy to Coolify
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
          --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
